# Generated by Django 4.1.1 on 2022-09-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pricingrule_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='RentalProperty',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='property',
            new_name='rental_property',
        ),
        migrations.RenameField(
            model_name='pricingrule',
            old_name='property',
            new_name='rental_property',
        ),
    ]
